version: "2"

services:
  db:
    image: mysql
    restart: always

  elasticsearch:
    image: elasticsearch:7.14.1
    restart: always

  redis:
    image: redis

  app:
    build: .
    restart: always
    depends_on:
      - 'db'
      - 'elasticsearch'
      - 'redis'
    ports:
      - '3002:3002'

  sidekiq:
    build: .
    restart: always
    depends_on:
      - 'app'
      - 'db'
      - 'elasticsearch'
      - 'redis'
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh